### ISSUE TITLE
Cross-lingual  search for contracts starting from Italian  returning back suppliers

### ISSUE THREAD

**Issue by divnadjordjevic** [TBFY/knowledge-graph-API#29]
Given input text in Italian  a functionality that would find similar closed contracts for other languages during the last 12 months ( jurisdiction, not Italian) not open tenders but closed contract notices in the TBFY knowledge graph and  retrieve list of the Suppliers that have  won those contracts in other jurisdictions  so non –Italian companies.

**Comment by divnadjordjevic** [comment]
@fyedro @cbadenes

**Comment by divnadjordjevic** [comment]
@fyedro @cbadenes

**Comment by cbadenes** [comment]
Added support for texts written in Italian to identify similar documents in other languages (English, Spanish, French and even Italian) through the Search API. It remains to introduce more complex concepts in the service, such as Organization or Tender,  to directly discover relationships at these levels.
