### ISSUE TITLE
Order criteria

### ISSUE THREAD

**Issue by cmorenilla** [TBFY/knowledge-graph-API#34]
Please, could you tell us how to set order criteria in list API services?
I.E   get tender list order by published date

Thanks

**Comment by fyedro** [comment]
Not a trivial question. We could sort the results by a preset parameter but to be able to order dynamically depending on the parameter chosen, we need time to develop it.

**Comment by fyedro** [comment]
Developed. Documentation available at https://github.com/TBFY/knowledge-graph-API/wiki
We will talk to SINTEF to try to improve the response time by expanding the heap memory
