### ISSUE TITLE
More query filters

### ISSUE THREAD

**Issue by cmorenilla** [TBFY/knowledge-graph-API#36]
In COPIN we need filter data using more criteria than “status”.  In particular by text in names, descriptions, titles or codes, or by dates.
Could you tell us if tell us if it is planned?

Thanks

**Comment by fyedro** [comment]
Added filter by description in several resources, documentation will be updated soon

**Comment by fyedro** [comment]
I regret to inform that this feature is not considered in the core API because such added value should be offered at a higher level. This issue doesn't correspond to the scope of the core API.

**Comment by fyedro** [comment]
Filtering by date finished. Example:
https://tbfy.librairy.linkeddata.es/api/contractingProcess?start_dt=2019-04-29T00:00:00
