### ISSUE TITLE
Awarded companies

### ISSUE THREAD

**Issue by cmorenilla** [TBFY/knowledge-graph-API#38]
**NEED**
We would need to know the number of unique awarded enterprises in the last months (since the Knowledge graph has data),  and if it’s posible, to get a the list of them (name and CIF).
We need this because we want to buy the data “size of the companies” (nº of employees), just for awarded enterprises. 
With this, we can identify SMEs and the relation with the type of contracts that they can win with more possibilities. 
The price depends on the number of enterprises. Ref.

**PROPOSAL**
Pre-condition: 
Classify companies by number of employees. Example:
- Type A	employees <=  1.000  
- Type B	 1.000 < employees <=  5.000  
- Type C	 5.000 < employees <= 15.000
- Type D	15.000 < employees <= 50.000
- Type E  50.000 < employees 

Create queries to provide information. Examples:
- number of awarded companies group by type (A, B, C, D, E)
- data (number of employees, CIF, country, cnae, ...) of awarded companies of a type (A, B, C, D, E)

**Comment by fyedro** [comment]
Created a notebook with many of the requests:
https://github.com/TBFY/knowledge-graph-API/blob/master/notebooks/Suppliers_v1.ipynb
