### ISSUE TITLE
Not all knowledge-graph-API queries work

### ISSUE THREAD

**Issue by Merlondio** [TBFY/knowledge-graph-API#40]
Another problem that we are seeing is that the APIs indicated in the documentation of https://github.com/TBFY/knowledge-graph-API/wiki not all WS return data. There are some that return an empty data set.
Examples that always return empty data, even with the examples indicated on the Wiki 
http://tbfy.librairy.linkeddata.es/kg-api/contract/ocds-0c46vo-0001-5c5b0cd0-1770-4709-813a-3f8eaa080a5b_c5d8150f-73d5-4905-b29b-23f428beaabd/document
http://tbfy.librairy.linkeddata.es/kg-api/award/ocds-0c46vo-0001-5c5b0cd0-1770-4709-813a-3f8eaa080a5b_c5d8150f-73d5-4905-b29b-23f428beaabd/item

In other cases:
http://tbfy.librairy.linkeddata.es/kg-api/tender/ocds-0c46vo-0001-02f25542-7be1-42f8-a670-873fe39f2cd7_ocds-b5fd17-63bc3042-75be-4082-8cae-6d9a9eb23b70-cf-0001300d1r000001nvobeai1/item
This is the one given as example and it works ok.

But if we use an ID returned in the generic tender query http://tbfy.librairy.linkeddata.es/kg-api/tender, as for example ocds-0c46vo-0049-2710240_2710240
http://tbfy.librairy.linkeddata.es/kg-api/tender/ocds-0c46vo-0049-2710240_2710240
                It is a valid ID, since in this query it returns us query data, such as the description
http://tbfy.librairy.linkeddata.es/kg-api/tender/ocds-0c46vo-0049-2710240_2710240/item
But when we consult the item, it returns an empty data set

Due to this we cannot obtain complete information of the tender to be able to analyse the data.

**Comment by fyedro** [comment]
Solved by email
