### ISSUE TITLE
Filter kg-api by date

### ISSUE THREAD

**Issue by Merlondio** [TBFY/knowledge-graph-API#41]
Hello, 

Can you tell me if there is a way to search the KG-API by date? Or if it could be implemented.
	In this case I'm talking about the access to the API by the URL http://tbfy.librairy.linkeddata.es/kg-api/tender 

https://github.com/TBFY/knowledge-graph-API/wiki/Tender

From the documentation, you can only search by the fields "id, title, description, status"
But this limits that when we search we always get the same data, that is, if I search by status and limit to 100 results, I have no way to find the next 100 results.
	If there was a search by date, I could go through time periods.

Thank you

**Comment by fyedro** [comment]
Being developed in issue #36
